const countryList = [
    "Andorra",
    "Vereinigte Arabische Emirate",
    "Afghanistan",
    "Antigua und Barbuda",
    "Anguilla",
    "Albanien",
    "Armenien",
    "Niederländische Antillen",
    "Angola",
    "Antarktis",
    "Argentinien",
    "Amerikanisch-Samoa",
    "Österreich",
    "Australien",
    "Aruba",
    "Åland",
    "Aserbaidschan",
    "Bosnien und Herzegowina",
    "Barbados",
    "Bangladesch",
    "Belgien",
    "Burkina Faso",
    "Bulgarien",
    "Bahrain",
    "Burundi",
    "Benin",
    "Bermuda",
    "Brunei Darussalam",
    "Bolivien",
    "Brasilien",
    "Bahamas",
    "Bhutan",
    "Bouvetinsel",
    "Botswana",
    "Belarus (Weißrussland)",
    "Belize",
    "Kanada",
    "Kokosinseln (Keelinginseln)",
    "Kongo",
    "Zentralafrikanische Republik",
    "Republik Kongo",
    "Schweiz",
    "Elfenbeinküste",
    "Cookinseln",
    "Chile",
    "Kamerun",
    "China, Volksrepublik",
    "Kolumbien",
    "Costa Rica",
    "Kuba",
    "Kap Verde",
    "Weihnachtsinsel",
    "Zypern",
    "Tschechische Republik",
    "Deutschland",
    "Dschibuti",
    "Dänemark",
    "Dominica",
    "Dominikanische Republik",
    "Algerien",
    "Ecuador",
    "Estland (Reval)",
    "Ägypten",
    "Westsahara",
    "Eritrea",
    "Spanien",
    "Äthiopien",
    "Finnland",
    "Fidschi",
    "Falklandinseln (Malwinen)",
    "Mikronesien",
    "Färöer",
    "Frankreich",
    "Gabun",
    "Großbritannien und Nordirland",
    "Grenada",
    "Georgien",
    "Französisch-Guayana",
    "Guernsey (Kanalinsel)",
    "Ghana",
    "Gibraltar",
    "Grönland",
    "Gambia",
    "Guinea",
    "Guadeloupe",
    "Äquatorialguinea",
    "Griechenland",
    "Südgeorgien und die Südl. Sandwichinseln",
    "Guatemala",
    "Guam",
    "Guinea-Bissau",
    "Guyana",
    "Hongkong",
    "Heard- und McDonald-Inseln",
    "Honduras",
    "Kroatien",
    "Haiti",
    "Ungarn",
    "Indonesien",
    "Irland",
    "Israel",
    "Insel Man",
    "Indien",
    "Britisches Territorium im Indischen Ozean",
    "Irak",
    "Iran",
    "Island",
    "Italien",
    "Jersey (Kanalinsel)",
    "Jamaika",
    "Jordanien",
    "Japan",
    "Kenia",
    "Kirgisistan",
    "Kambodscha",
    "Kiribati",
    "Komoren",
    "St. Kitts und Nevis",
    "Nordkorea",
    "Südkorea",
    "Kuwait",
    "Kaimaninseln",
    "Kasachstan",
    "Laos",
    "Libanon",
    "St. Lucia",
    "Liechtenstein",
    "Sri Lanka",
    "Liberia",
    "Lesotho",
    "Litauen",
    "Luxemburg",
    "Lettland",
    "Libyen",
    "Marokko",
    "Monaco",
    "Moldawien",
    "Madagaskar",
    "Marshallinseln",
    "Mazedonien",
    "Mali",
    "Myanmar (Burma)",
    "Mongolei",
    "Macau",
    "Nördliche Marianen",
    "Martinique",
    "Mauretanien",
    "Montserrat",
    "Malta",
    "Mauritius",
    "Malediven",
    "Malawi",
    "Mexiko",
    "Malaysia",
    "Mosambik",
    "Namibia",
    "Neukaledonien",
    "Niger",
    "Norfolkinsel",
    "Nigeria",
    "Nicaragua",
    "Niederlande",
    "Norwegen",
    "Nepal",
    "Nauru",
    "Niue",
    "Neuseeland",
    "Oman",
    "Panama",
    "Peru",
    "Französisch-Polynesien",
    "Papua-Neuguinea",
    "Philippinen",
    "Pakistan",
    "Polen",
    "St. Pierre und Miquelon",
    "Pitcairninseln",
    "Puerto Rico",
    "Palästina",
    "Portugal",
    "Palau",
    "Paraguay",
    "Katar",
    "Réunion",
    "Rumänien",
    "Russische Föderation",
    "Ruanda",
    "Saudi-Arabien",
    "Salomonen",
    "Seychellen",
    "Sudan",
    "Schweden",
    "Singapur",
    "St. Helena",
    "Slowenien",
    "Svalbard und Jan Mayen",
    "Slowakei",
    "Sierra Leone",
    "San Marino",
    "Senegal",
    "Somalia",
    "Suriname",
    "São Tomé und Príncipe",
    "El Salvador",
    "Syrien",
    "Swasiland",
    "Turks- und Caicosinseln",
    "Tschad",
    "Französische Süd- und Antarktisgebiete",
    "Togo",
    "Thailand",
    "Tadschikistan",
    "Tokelau",
    "Timor-Leste",
    "Turkmenistan",
    "Tunesien",
    "Tonga",
    "Türkei",
    "Trinidad und Tobago",
    "Tuvalu",
    "Taiwan",
    "Tansania",
    "Ukraine",
    "Uganda",
    "Amerikanisch-Ozeanien",
    "Vereinigte Staaten von Amerika",
    "Uruguay",
    "Usbekistan",
    "Vatikanstadt",
    "St. Vincent und die Grenadinen",
    "Venezuela",
    "Britische Jungferninseln",
    "Amerikanische Jungferninseln",
    "Vietnam",
    "Vanuatu",
    "Wallis und Futuna",
    "Samoa",
    "Jemen",
    "Mayotte",
    "Südafrika",
    "Sambia",
    "Simbabwe",
    "Serbien",
    "Montenegro",
    "Saint-Barthélemy",
    "Bonaire",
    "Curaçao",
    "Saint-Martin",
    "Sint Maarten",
    "Sudsudan"
];

export class CountryListHandler {
    public getCountryList(filterQuery: string): string[] {
        return countryList.filter(country=>{
            return country.toLowerCase().indexOf(filterQuery.toLowerCase()) > -1;
        });
    }
}